CXX = g++
CXXFLAGS = -Wall -Werror -std=c++11

TARGET = z1942130_project1
SOURCE = assign1.cpp
HEADER = assign1.h

$(TARGET): $(SOURCE) $(HEADER)
	$(CXX) $(CXXFLAGS) $(SOURCE) -o $(TARGET)

clean:
	rm -f $(TARGET)

.PHONY: clean
