#
# PROGRAM:    Assignment 1
# PROGRAMMER: David Flowers II
# LOGON ID:   z1942130
# DATE DUE:   09/02/2022
#
    
# Compiler variables
CXX = g++
CXXFLAGS = -Wall -Werror -std=c++11
        
# Rule to link object code files to create executable file
introduction: introduction.cc
	$(CXX) $(CXXFLAGS) -o introduction $^
